export default [
    "Dinner plate",
    "Bread plate",
    "Salad plate",
    "Water glass",
    "Wine glass",
    "Coffee cups with saucer",
    "Silverware setting",
    "Linen or paper napkin",
    "Tablecloth",
    "Table centerpiece",
    "Salt and pepper shaker",
    "Sugar holder",
    "Butter holder",
    "Serving Equipment",
    "Serving tray",
    "Bus tub",
    "Water pitcher",
    "Buffet Equipment",
    "Plate",
    "Silverware roll",
    "Bread basket",
    "Chaffing dish",
    "Fuel cell for chaffing dishes",
    "Lighter or matches for fuel cell",
    "Tongs",
    "Serving spoon",
    "Spatula",
    "Cutting board (for beefs, hams, and turkey)",
    "Sharp knife for cutting",
    "Rags (for spills)",
    "Decorations (seasonal flowers, etc.)",
    "Coffee/Beverage Station",
    "Air-pots for coffee, decaf, and hot water",
    "Water pitcher",
    "Iced tubs for soda, juice and other cold drink",
    "Drinking straw",
    "Drink stirrer",
    "Cocktail napkin",
    "Coffee cup",
    "Water glass",
    "Basket of assorted teas and or hot cocoa",
    "Basket of sugar packet",
    "Small wastebasket",
    "Cambro",
    "Garbage bags for dirty linen",
    "Extra bus tub for dirty dishes",
    "Disposable containers for food storage",
    "Plastic wrap",
    "Tin foil",
    "Extra serving utensil",
    "Jug of water",
    "Hand sanitizer",
    "Beef",
    "Grass Fed Chicken",
    "Free Range Chicken",
    "Organic Chicken",
    "Turkey",
    "Skinned Chicken",
    "Pork",
    "Partridge",
    "Meat Stock",
    "Keema",
    "Mutton Liver",
    "Ham",
    "Kidney Meat",
    "Crab",
    "Chicken Stock",
    "Chicken Liver",
    "Chicken",
    "Chops",
    "Lamb Meat",
    "Quail",
    "Mutton",
    "Bacon",
    "Bok Choy",
    "Snake Beans",
    "Sorrel Leaves",
    "Rocket Leaves",
    "Cherry Tomatoes",
    "Kaffir Lime",
    "Plantain",
    "Turnip",
    "Sweet Potatoes",
    "Round Gourd",
    "Ridge Gourd",
    "Pimiento",
    "Spinach",
    "Onion",
    "Mustard Leaves",
    "Mushroom",
    "Radish",
    "Shallots",
    "Lettuce",
    "Leek",
    "Pumpkin",
    "Yam",
    "Jalapeno",
    "Jackfruit",
    "Horseradish",
    "Spring Onion"
];
