export default [
  "Samsung Manufacturing Holiday Party",
  "Melissa's Lunch/Celebration",
  "Hines Holiday Happy Hour",
  "Birthday Event!",
  "Victoria Davila Birthday Event!",
  "HLT Tour 2016",
  "Elan's Bar Mitzvah",
  "Shana's 30th Birthday",
  "East Town",
  "OCF - OR Community Foundation",
  "Heather's 30th Birthday",
  "Ticor Title",
  "Chase",
  "Ferenzi Networking Event",
  "Exusia",
  "Draft Party",
  "Mike Kubinski",
  "Title Source - Map It Outing",
  "Organically Grown Company",
  "Corkill Insurance Agency",
  "Del: Trader Joes",
  "Tyrone Scott Bowling Event",
  "KVUE",
  "Martin Reservation",
  "Mason's 18th Birthday Party!",
  "BEST OF THE BOWL",
  "Tomisha's Birthday",
  "Rebecca's Karaoke Event",
  "Bug Cast/Crew Wrap Party",
  "Radar",
  "McDonagh Wedding Reception",
  "Travel Portland",
  "Clint Moore Bowling Party",
  "Rock Hall Luncheon",
  "Jaden's Birthday",
  "Blackbaud Happy Hour",
  "QL Underwriters",
  "Auto Week Outing",
  "D-Tools Austin Training",
  "Tommy Skinner"
];
