export default [
    "Artisan Bread With Infused Spreads",
    "Modern Caesar",
    "Petite Filet Mignon",
    "Certified Angus Beef Hanger Steak",
    "Barbecue Scottish Salmon",
    "Gulf Shrimp Sea Scallops",
    "Free Range Lemon Rosemary Brick Chicken",
    "Grilled Portobello Mushroom With Butternut Squash",
    "Truffled Mashed Potatoes",
    "Spicy Thai Green Beans",
    "Cheesecake",
    "Coffee Tea And Soft Drinks",
    "Shrimp Cocktail",
    "Petite Filet Shrimp",
    "12 Oz Main Filet Mignon",
    "Craftsman Prime Ribeye",
    "Certified Angus Beef Hanger Steak",
    "Chilean Sea Bass",
    "Creamed Spinach",
    "Grilled High Country Asparagus",
    "Crème Brûlée"
];
